/* Shared placeholder data used by every mockup. Not wired to any live API. */
window.MOCK = (() => {
  const now = new Date();
  const iso = (d) => d.toISOString();
  const plusMin = (m) => { const d = new Date(now); d.setMinutes(d.getMinutes() + m); return d; };
  const atHour = (h, m = 0) => { const d = new Date(now); d.setHours(h, m, 0, 0); return d; };
  const daysAgo = (n, h = 10, m = 0) => { const d = new Date(now); d.setDate(d.getDate() - n); d.setHours(h, m, 0, 0); return d.toISOString(); };

  const rep = {
    id: 's7OG2BM94q7uNRsHLqM7',
    name: 'Amir Khan',
    initials: 'AK',
    email: 'amir@i3media.net',
    ext: '204',
    avatarColor: '#6366f1',
  };

  const stats = {
    callbacksOverdue: 3,
    callbacksToday: 7,
    callbacksLater: 12,
    meetingsPending: 2,
    callReady: 42,
    sent: 4,
    dialed: 11,
    connected: 3,
  };

  // 24 leads — enough to demonstrate pagination/focus behavior.
  const leads = [
    {
      id: 'L-1001', name: 'Sofia Marchetti', title: 'Managing Director',
      companyName: 'Marchetti & Partners', subSector: 'Consultancies',
      priority: 'hot', status: 'to_call_back',
      phone: '+44 20 7946 1023', directPhone: '+44 20 7946 1024',
      email: 'sofia@marchettipartners.co.uk', companyWebsite: 'https://marchettipartners.co.uk',
      callbackAt: iso(plusMin(15)), disposition: 'Interested',
      noteCount: 4, source: 'hs_pd', companyPeerCount: 3,
      peerPeople: [{ name: 'James Rowe', title: 'Head of Ops' }, { name: 'Priya Kapoor', title: 'Marketing Lead' }],
      notes: [
        { who:'Amir Khan', when: daysAgo(1, 15, 22), kind:'call',   text:'Spoke to gatekeeper Jenny — Sofia in a meeting until 3pm. Emailed intro deck and asked her to book a callback for tomorrow.' },
        { who:'Zain',      when: daysAgo(3,  9, 40), kind:'call',   text:'Left voicemail on office line. Direct dial goes to switchboard after 5pm — stick to daytime.' },
        { who:'System',    when: daysAgo(9, 11,  0), kind:'system', text:'Enrolled from HS/PD import · wave 2 · tier 1.' },
      ],
    },
    {
      id: 'L-1002', name: 'David Chen', title: 'Founder',
      companyName: 'Northline Studio', subSector: 'E-Commerce · Fashion',
      priority: 'warm', status: 'wants_more_info',
      phone: '+44 161 555 3311', directPhone: '',
      email: 'david@northline.studio', companyWebsite: 'https://northline.studio',
      callbackAt: iso(atHour(14, 30)), disposition: 'Interested',
      noteCount: 2, source: 'google_maps', companyPeerCount: 1, peerPeople: [],
      notes: [
        { who:'Amir Khan', when: daysAgo(2, 11, 15), kind:'call', text:'Chatted for 8 min. Wants a proper deck before committing to a demo. Sending the E-comm case-study pack today.' },
        { who:'Amir Khan', when: daysAgo(2, 11, 25), kind:'email', text:'Sent E-comm case-study pack via Mailgun (open receipt pending).' },
      ],
    },
    {
      id: 'L-1003', name: 'Ella Whitmore', title: 'Owner',
      companyName: 'Whitmore Legal', subSector: 'Professional Services',
      priority: 'warm', status: 'to_contact',
      phone: '+44 113 555 2299', directPhone: '+44 113 555 2298',
      email: 'ella@whitmorelegal.co.uk', companyWebsite: 'https://whitmorelegal.co.uk',
      callbackAt: null, disposition: '',
      noteCount: 0, source: 'hs_pd', companyPeerCount: 2,
      peerPeople: [{ name: 'Ravi Shah', title: 'Practice Manager' }],
    },
    {
      id: 'L-1004', name: 'Marcus Bell', title: 'Sales Director',
      companyName: 'Bell Freight', subSector: 'Transport & Logistics',
      priority: 'cold', status: 'no_answer',
      phone: '+44 1483 555 7712', directPhone: '',
      email: 'marcus@bellfreight.com', companyWebsite: 'https://bellfreight.com',
      callbackAt: iso(atHour(16, 0)), disposition: 'Left voicemail',
      noteCount: 1, source: 'hs_pd', companyPeerCount: 1, peerPeople: [],
      notes: [
        { who:'Amir Khan', when: daysAgo(1,  9, 12), kind:'call', text:'VM — receptionist said Marcus is on the road until 4pm. Retry after lunch.' },
      ],
    },
    {
      id: 'L-1005', name: 'Aisha Rahman', title: 'CEO',
      companyName: 'Rahman Recruit', subSector: 'Recruitment & HR',
      priority: 'hot', status: 'contacted',
      phone: '+44 20 7946 7788', directPhone: '+44 7700 900 213',
      email: 'aisha@rahmanrecruit.com', companyWebsite: 'https://rahmanrecruit.com',
      callbackAt: iso(atHour(11, 45)), disposition: 'Interested',
      noteCount: 6, source: 'hs_pd', companyPeerCount: 1, peerPeople: [],
      notes: [
        { who:'Amir Khan', when: daysAgo(0,  9, 15), kind:'call', text:'Great intro call — 10 min. Very interested in the recruitment-vertical demo. Booked her in at 11:45 today for a pricing walkthrough.' },
        { who:'Amir Khan', when: daysAgo(0,  9, 20), kind:'note', text:'She mentioned her ops lead Aarav will join the callback. Prep the split-fee slide.' },
        { who:'Zain',      when: daysAgo(4, 14, 30), kind:'call', text:'First touch — answered, asked for a follow up in a few days.' },
      ],
    },
    {
      id: 'L-1006', name: 'Oliver Grant', title: 'Founder',
      companyName: 'Grant Cyber', subSector: 'Cyber Security',
      priority: 'warm', status: 'to_contact',
      phone: '+44 131 555 8823', directPhone: '',
      email: 'oliver@grantcyber.io', companyWebsite: 'https://grantcyber.io',
      callbackAt: null, disposition: '', noteCount: 0, source: 'google_maps',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1007', name: 'Priyanka Verma', title: 'Head of Marketing',
      companyName: 'Verma Health', subSector: 'Healthcare',
      priority: 'hot', status: 'to_call_back',
      phone: '+44 20 7946 0088', directPhone: '+44 7700 900 445',
      email: 'priyanka@vermahealth.co.uk', companyWebsite: 'https://vermahealth.co.uk',
      callbackAt: iso(plusMin(-45)), disposition: 'Interested',
      noteCount: 3, source: 'hs_pd', companyPeerCount: 2,
      peerPeople: [{ name: 'Tom Green', title: 'Ops Manager' }],
      notes: [
        { who:'Amir Khan', when: daysAgo(2, 16, 10), kind:'call', text:'Answered on the direct — v keen, has budget approved. Booked a 30-min slot but she has requested confirmation email.' },
        { who:'Amir Khan', when: daysAgo(2, 16, 40), kind:'email', text:'Sent Zoom link + agenda for the discovery call.' },
      ],
    },
    {
      id: 'L-1008', name: 'Liam O\u2019Brien', title: 'Director',
      companyName: 'O\u2019Brien Studios', subSector: 'Consultancies',
      priority: 'warm', status: 'wants_more_info',
      phone: '+44 20 7946 1199', directPhone: '',
      email: 'liam@obrienstudios.co.uk', companyWebsite: 'https://obrienstudios.co.uk',
      callbackAt: iso(atHour(15, 15)), disposition: 'Send email',
      noteCount: 1, source: 'hs_pd', companyPeerCount: 1, peerPeople: [],      notes: [
        { who:'Amir Khan', when: daysAgo(3, 10, 30), kind:'call', text:'Asked for a written summary before he\'ll commit to a demo. Sending short one-pager today.' },
      ],    },
    {
      id: 'L-1009', name: 'Hannah Bennett', title: 'Managing Partner',
      companyName: 'Bennett Advisory', subSector: 'Consultancies',
      priority: 'cold', status: 'no_answer',
      phone: '+44 20 7946 3021', directPhone: '',
      email: 'hannah@bennett-advisory.co.uk', companyWebsite: 'https://bennett-advisory.co.uk',
      callbackAt: null, disposition: 'No answer',
      noteCount: 2, source: 'hs_pd', companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1010', name: 'Yusuf Ali', title: 'Owner',
      companyName: 'Ali Interiors', subSector: 'E-Commerce · Home',
      priority: 'warm', status: 'to_contact',
      phone: '+44 121 555 4477', directPhone: '',
      email: 'yusuf@aliinteriors.co.uk', companyWebsite: 'https://aliinteriors.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'google_maps',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1011', name: 'Grace Nakamura', title: 'CEO',
      companyName: 'Nakamura & Co', subSector: 'Recruitment & HR',
      priority: 'hot', status: 'to_call_back',
      phone: '+44 20 7946 6612', directPhone: '+44 7700 900 987',
      email: 'grace@nakamura.co', companyWebsite: 'https://nakamura.co',
      callbackAt: iso(atHour(9, 30)), disposition: 'Interested',
      noteCount: 5, source: 'hs_pd', companyPeerCount: 2,
      peerPeople: [{ name: 'Jon Reid', title: 'BD Lead' }],
      notes: [
        { who:'Amir Khan', when: daysAgo(1, 12,  0), kind:'call', text:'Very warm — evaluating three vendors, we\'re shortlisted. Booked 09:30 today for pricing + case studies.' },
        { who:'Amir Khan', when: daysAgo(6, 15, 30), kind:'call', text:'First conversation. She asked for a proposal doc; sent Notion link.' },
      ],
    },
    {
      id: 'L-1012', name: 'Faisal Iqbal', title: 'Director',
      companyName: 'Iqbal Freight', subSector: 'Transport & Logistics',
      priority: 'warm', status: 'to_contact',
      phone: '+44 161 555 9080', directPhone: '',
      email: 'faisal@iqbalfreight.co.uk', companyWebsite: 'https://iqbalfreight.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1013', name: 'Chloe Fairbank', title: 'Head of Sales',
      companyName: 'Fairbank Digital', subSector: 'Consultancies',
      priority: 'cold', status: 'wants_more_info',
      phone: '+44 20 7946 2244', directPhone: '',
      email: 'chloe@fairbank.digital', companyWebsite: 'https://fairbank.digital',
      callbackAt: iso(atHour(17, 0)), disposition: 'Send email',
      noteCount: 1, source: 'hs_pd', companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1014', name: 'Noah Reeves', title: 'Owner',
      companyName: 'Reeves Roofing', subSector: 'Trades',
      priority: 'cold', status: 'no_answer',
      phone: '+44 1234 555 0210', directPhone: '',
      email: 'noah@reevesroofing.co.uk', companyWebsite: '',
      callbackAt: null, disposition: 'No answer', noteCount: 3, source: 'google_maps',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1015', name: 'Sara El-Sayed', title: 'Founder',
      companyName: 'El-Sayed Wellness', subSector: 'Healthcare',
      priority: 'warm', status: 'to_contact',
      phone: '+44 20 7946 5544', directPhone: '',
      email: 'sara@elsayedwellness.co.uk', companyWebsite: 'https://elsayedwellness.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1016', name: 'Ben Carter', title: 'Sales Director',
      companyName: 'Carter Auto', subSector: 'Automotive',
      priority: 'warm', status: 'to_call_back',
      phone: '+44 20 7946 3355', directPhone: '',
      email: 'ben@carterauto.co.uk', companyWebsite: 'https://carterauto.co.uk',
      callbackAt: iso(atHour(13, 0)), disposition: 'Interested',
      noteCount: 2, source: 'hs_pd', companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1017', name: 'Layla Ahmed', title: 'Head of Growth',
      companyName: 'Ahmed Bloom', subSector: 'E-Commerce · Beauty',
      priority: 'warm', status: 'to_contact',
      phone: '+44 20 7946 7799', directPhone: '',
      email: 'layla@ahmedbloom.com', companyWebsite: 'https://ahmedbloom.com',
      callbackAt: null, disposition: '', noteCount: 0, source: 'google_maps',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1018', name: 'Isaac Patel', title: 'Managing Director',
      companyName: 'Patel Print', subSector: 'Print & Packaging',
      priority: 'cold', status: 'no_answer',
      phone: '+44 20 7946 3399', directPhone: '',
      email: 'isaac@patelprint.co.uk', companyWebsite: 'https://patelprint.co.uk',
      callbackAt: null, disposition: 'Left voicemail', noteCount: 1, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1019', name: 'Millie Watson', title: 'Founder',
      companyName: 'Watson Studios', subSector: 'Consultancies',
      priority: 'warm', status: 'to_contact',
      phone: '+44 20 7946 4488', directPhone: '',
      email: 'millie@watsonstudios.co.uk', companyWebsite: 'https://watsonstudios.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1020', name: 'Rohan Desai', title: 'Head of Ops',
      companyName: 'Desai Supply', subSector: 'Transport & Logistics',
      priority: 'warm', status: 'to_contact',
      phone: '+44 20 7946 8811', directPhone: '',
      email: 'rohan@desaisupply.co.uk', companyWebsite: 'https://desaisupply.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1021', name: 'Emily Foster', title: 'Managing Director',
      companyName: 'Foster Analytics', subSector: 'Consultancies',
      priority: 'hot', status: 'wants_more_info',
      phone: '+44 20 7946 1122', directPhone: '',
      email: 'emily@fosteranalytics.co.uk', companyWebsite: 'https://fosteranalytics.co.uk',
      callbackAt: null, disposition: 'Send email', noteCount: 2, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1022', name: 'Zain Mehta', title: 'Founder',
      companyName: 'Mehta Craft', subSector: 'E-Commerce · Home',
      priority: 'warm', status: 'to_contact',
      phone: '+44 20 7946 9922', directPhone: '',
      email: 'zain@mehtacraft.co.uk', companyWebsite: 'https://mehtacraft.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1023', name: 'Nora Sinclair', title: 'Director',
      companyName: 'Sinclair PR', subSector: 'Marketing & PR',
      priority: 'warm', status: 'no_answer',
      phone: '+44 20 7946 7754', directPhone: '',
      email: 'nora@sinclairpr.co.uk', companyWebsite: 'https://sinclairpr.co.uk',
      callbackAt: null, disposition: 'No answer', noteCount: 1, source: 'hs_pd',
      companyPeerCount: 1, peerPeople: [],
    },
    {
      id: 'L-1024', name: 'Sam Ward', title: 'Owner',
      companyName: 'Ward Fitness', subSector: 'Health & Wellness',
      priority: 'cold', status: 'to_contact',
      phone: '+44 20 7946 0011', directPhone: '',
      email: 'sam@wardfitness.co.uk', companyWebsite: 'https://wardfitness.co.uk',
      callbackAt: null, disposition: '', noteCount: 0, source: 'google_maps',
      companyPeerCount: 1, peerPeople: [],
    },
  ];

  const calendar = [
    { time: iso(atHour(9, 30)),  kind: 'callback', title: 'Grace Nakamura',    subtitle: 'Nakamura & Co · discovery follow-up' },
    { time: iso(atHour(10, 0)),  kind: 'activity', title: 'Team huddle',       subtitle: 'Slack #sales · 15 min' },
    { time: iso(atHour(11, 45)), kind: 'callback', title: 'Aisha Rahman',      subtitle: 'Rahman Recruit · pricing walkthrough' },
    { time: iso(atHour(13, 0)),  kind: 'callback', title: 'Ben Carter',        subtitle: 'Carter Auto · demo prep' },
    { time: iso(atHour(14, 0)),  kind: 'meeting',  title: 'Sofia Marchetti',   subtitle: 'Marchetti & Partners · Zoom · 30 min' },
    { time: iso(atHour(14, 30)), kind: 'callback', title: 'David Chen',        subtitle: 'Northline Studio · brief callback' },
    { time: iso(atHour(15, 15)), kind: 'callback', title: 'Liam O\u2019Brien', subtitle: 'O\u2019Brien Studios · send info pack' },
    { time: iso(atHour(16, 0)),  kind: 'callback', title: 'Marcus Bell',       subtitle: 'Bell Freight · retry attempt' },
    { time: iso(atHour(17, 0)),  kind: 'callback', title: 'Chloe Fairbank',    subtitle: 'Fairbank Digital · info follow-up' },
  ];

  const STATUS_LABELS = {
    to_contact: 'To contact',
    to_call_back: 'Call back',
    wants_more_info: 'Wants info',
    no_answer: 'No answer',
    contacted: 'Contacted',
    qualified: 'Qualified',
    converted: 'Converted',
    not_interested: 'Not interested',
  };

  return { rep, stats, leads, calendar, STATUS_LABELS, now: iso(now) };
})();
